-- DDL - CREATE
CREATE TABLE DEPT_DDL (
	DEPTNO	NUMBER(2),
	DNAME 	VARCHAR2(14),
	LOC		VARCHAR2(13)
);

-- DROP
DROP TABLE DEPT_DDL;

-- DDL용 테이블 복사
CREATE TABLE EMP_ALTER
	AS SELECT * FROM EMP;

SELECT * FROM EMP_ALTER;

-- ALTER - 테이블 변경(컬럼명 변경, 컬럼 추가, 컬럼 삭제, ...)
ALTER TABLE EMP_ALTER
  ADD PHONE VARCHAR2(20);

ALTER TABLE EMP_ALTER
  ADD (
	FAX		VARCHAR2(20),
	EMAIL 	VARCHAR2(100),
	ADDRESS VARCHAR2(200)
);

-- ALTER 컬럼(열)이름 변경
 ALTER TABLE EMP_ALTER
RENAME COLUMN PHONE TO TEL;

-- ALTER 컬럼(열) 자료형 변경
 ALTER TABLE EMP_ALTER
MODIFY EMPNO NUMBER(8); 

-- ALTER 특정컬럼 삭제
ALTER TABLE EMP_ALTER
 DROP COLUMN FAX;

-- 여러컬럼 삭제시는 COLUMN 키워드 대신 소괄호 사용
ALTER TABLE EMP_ALTER
 DROP (
	EMAIL, ADDRESS
);

-- RENAME 객체 이름 변경
RENAME EMP_ALTER TO EMP_RENAME;

-- TRUNCATE 객체 중 테이블 데이터 초기화(완전삭제)
-- COMMIT, ROLLBACK 안됨(트랜잭션 불가)
SELECT * FROM EMP_RENAME;

TRUNCATE TABLE EMP_RENAME;