-- 객체

-- 데이터 사전
-- 사용중인 객체들을 확인하는 역할
SELECT *
FROM USER_INDEXES;

SELECT *
FROM USER_VIEWS; -- 스키마 SYS 내 위치

-- USER_OBJECT, USER_RULES, USER_TABLES, USER_INDEXES, USER_VIEWS, ...
-- USER_SEQUENCES

SELECT *
  FROM DICTIONARY
 WHERE TABLE_NAME LIKE 'USER_%'
 ORDER BY TABLE_NAME;

-- 인덱스 생성
-- IDX(인덱스 접두어)_테이블_인덱스컬럼
CREATE INDEX IDX_EMP_SAL
    ON EMP(SAL);

-- 인덱스 생성
DROP INDEX IDX_EMP_SAL;

-- 뷰
CREATE VIEW VW_EMP_20
    AS (SELECT EMPNO, ENAME, JOB, DEPTNO
  		  FROM EMP
 		 WHERE DEPTNO = 20);

SELECT * FROM VW_EMP_20;

SELECT * 
  FROM VW_EMP_20 v, DEPT d
 WHERE v.DEPTNO = d.DEPTNO;

-- 삭제
DROP VIEW VW_EMP_20;

-- 뷰2
CREATE OR REPLACE VIEW VW_DEPT_ALL
	AS (SELECT * FROM DEPT);

SELECT * FROM VW_DEPT_ALL;

INSERT INTO VW_DEPT_ALL (DEPTNO, DNAME, LOC)
VALUES ('90', 'TEST', 'NONE');

-- 시퀀스
-- 생성
CREATE SEQUENCE SEQ_BOARD
START WITH 1 -- 보통 1부터 시작
INCREMENT BY 1 -- 보통 1씩 증가
MAXVALUE 9999999 -- 또는 NOMAXVALUE
NOCYCLE -- MAXVALUE까지 가면 끝. CYCLE - MAX까지 가면 다시 1
NOCACHE;

-- 게시판 테이블 생성
CREATE TABLE BOARDTBL (
	BOARD_ID	NUMBER(7)	 PRIMARY KEY,
	TITLE		VARCHAR2(200)	NOT NULL,
	WRITER		VARCHAR2(50)	NOT NULL,
	CONTENTS	VARCHAR2(4000),
	REGDATE		DATE DEFAULT SYSDATE
);

-- 게시판 데이터 입력
INSERT INTO BOARDTBL
(BOARD_ID, TITLE, WRITER, CONTENTS)
VALUES
(SEQ_BOARD.NEXTVAL, '테스트 제목', '홍길동', '내용입니다');

INSERT INTO BOARDTBL
(BOARD_ID, TITLE, WRITER, CONTENTS)
VALUES
(SEQ_BOARD.NEXTVAL, '테스트2 제목', '홍길순', '새 내용입니다');

INSERT INTO BOARDTBL
(BOARD_ID, TITLE, WRITER, CONTENTS)
VALUES
(SEQ_BOARD.NEXTVAL, '테스트3 제목', '유고성', '새새 내용입니다');

SELECT * FROM BOARDTBL;

COMMIT;

-- 다음 시퀀스 확인
SELECT SEQ_BOARD.NEXTVAL FROM DUAL;

SELECT SEQ_BOARD.CURRVAL FROM DUAL;

-- 시퀸스 수정
ALTER SEQUENCE SEQ_BOARD
INCREMENT BY 2
CYCLE;

-- 시퀀스 삭제
DROP SEQUENCE SEQ_BOARD;

