-- 제약조건

-- 1. NOT NULL
CREATE TABLE TBL_NN (
	LOGIN_ID 	VARCHAR2(20) NOT NULL,
	LOGIN_PWD 	VARCHAR2(20) NOT NULL,
	TEL			VARCHAR2(20)
);

SELECT * FROM TBL_NN;

INSERT INTO TBL_NN (LOGIN_ID, LOGIN_PWD, TEL)
VALUES ('hugo95', '12345', NULL);

INSERT INTO TBL_NN (LOGIN_ID, LOGIN_PWD)
VALUES ('hugo76', '12345');

UPDATE TBL_NN
SET LOGIN_ID = NULL
WHERE LOGIN_ID = 'hugo95';

ALTER TABLE TBL_NN
RENAME CONSTRAINT SYS_C008530 TO NN_TBLNN_LOGINID;

-- 제약조건 삭제
ALTER TABLE TBL_NN
DROP CONSTRAINT NN_TBLNN_LOGINID;

-- 2. UNIQUE 중복을 허용하지 않음
CREATE TABLE TBL_UNQ (
	LOGIN_ID 	VARCHAR2(20) UNIQUE,
	LOGIN_PWD 	VARCHAR2(20) NOT NULL,
	TEL			VARCHAR2(20)
);

SELECT * FROM TBL_UNQ;

INSERT INTO TBL_UNQ (LOGIN_ID, LOGIN_PWD, TEL)
VALUES ('hugo95', '12345', NULL);

INSERT INTO TBL_UNQ (LOGIN_ID, LOGIN_PWD, TEL)
VALUES (NULL, '12345', '010-9999-0000');

-- 3. PRIMARY KEY, UNIQUE에 NOT NULL
CREATE TABLE TBL_PK (
	LOGIN_ID 	VARCHAR2(20) PRIMARY KEY,
	LOGIN_PWD 	VARCHAR2(20) NOT NULL,
	TEL			VARCHAR2(20)
);

SELECT * FROM TBL_PK;

INSERT INTO TBL_PK (LOGIN_ID, LOGIN_PWD, TEL)
VALUES ('hugo95', '12345', NULL);

INSERT INTO TBL_PK (LOGIN_ID, LOGIN_PWD, TEL)
VALUES (NULL, '12345', '010-9999-0000');

-- PK 생성
-- 하나 이상의 컬럼에 PK를 지정할 때
CREATE TABLE TBL_INFO (
	IDX 	NUMBER,
	CODE 	NUMBER,
	CNT		VARCHAR2(20),
	REGDATE	DATE DEFAULT SYSDATE,
	CONSTRAINT PK_TBL_INFO PRIMARY KEY (IDX, CODE)
);

SELECT * FROM TBL_INFO;

INSERT INTO TBL_INFO (IDX, CODE, CNT)
VALUES (1, 10, 'TEST1');

INSERT INTO TBL_INFO (IDX, CODE, CNT)
VALUES (1, 20, 'TEST2');

INSERT INTO TBL_INFO (IDX, CODE, CNT)
VALUES (2, 10, 'TEST2');

SELECT * FROM TBL_INFO
 WHERE IDX = 1
   AND CODE = 10;

-- 4. FOREIGN KEY - 타 테이블의 PK와 연관짓는 제약 조건
SELECT * FROM DEPT;
SELECT * FROM EMP;

-- FK를 참조하는 열에 존재하지 않는 데이터 입력
INSERT INTO EMP (EMPNO, ENAME, DEPTNO)
VALUES (9999, '홍길동', NULL);

INSERT INTO EMP (EMPNO, ENAME, DEPTNO)
VALUES (9998, '홍길순', 50);

-- FK 생성
CREATE TABLE DEPT_FK (
	DEPTNO 	NUMBER CONSTRAINT DEPT_FK_DEPTNO_PK PRIMARY KEY,
	DNAME 	VARCHAR2(20),
	LOC		VARCHAR2(13)
);

CREATE TABLE EMP_FK ( -- FK 지정용
	EMPNO	NUMBER			PRIMARY KEY, -- PK 이름 자동 생성
	ENAME 	VARCHAR2(20)	NOT NULL,
	JOB		VARCHAR2(10),
	MGR		NUMBER,
	DEPTNO NUMBER CONSTRAINT EMPFK_DEPTNO_FK REFERENCES DEPT_FK(DEPTNO) NOT NULL
);

-- INSERT ALL
INSERT ALL
INTO DEPT_FK (DEPTNO, DNAME, LOC) VALUES (10, 'DEV', 'SEOUL')
INTO DEPT_FK (DEPTNO, DNAME, LOC) VALUES (20, 'ACCOUNTING', 'INCHEON')
INTO DEPT_FK (DEPTNO, DNAME, LOC) VALUES (30, 'FINANCE', 'BUSAN')
SELECT * FROM DUAL;

SELECT * FROM DEPT_FK;

SELECT * FROM EMP_FK;

INSERT INTO EMP_FK (EMPNO, ENAME, DEPTNO)
VALUES (1000, '성유고', 20);

INSERT INTO EMP_FK (EMPNO, ENAME, DEPTNO, JOB, MGR)
VALUES (2000, '애슐리', 30, 'PRESIDENT', NULL);

DELETE FROM DEPT_FK WHERE DEPTNO = 20;

-- 5. CHECK - 지정한 조건식에 일치하는 데이터만 입력가능
CREATE TABLE TBL_CHK (
	LOGIN_ID 	VARCHAR2(20) PRIMARY KEY,
	LOGIN_PWD 	VARCHAR2(20) NOT NULL CHECK (LENGTH(LOGIN_PWD) > 7),
	TEL			VARCHAR2(20)
);

INSERT INTO TBL_CHK (LOGIN_ID, LOGIN_PWD, TEL)
VALUES ('ASHELY83', 'P12345s!', '010-9999-9898');

-- 6. DEFAULT - 기본값 처리
CREATE TABLE TBL_DFT (
	LOGIN_ID 	VARCHAR2(20) PRIMARY KEY,
	LOGIN_PWD 	VARCHAR2(20) DEFAULT '123456',
	TEL			VARCHAR2(20),
	REG_DATE	DATE DEFAULT SYSDATE
);

INSERT INTO TBL_DFT (LOGIN_ID, TEL)
VALUES ('ASHELY83', '010-9999-9898');

SELECT * FROM TBL_DFT;

-- 중요! CASCADE
CREATE TABLE DEPT_FK (
	DEPTNO 	NUMBER CONSTRAINT DEPT_FK_DEPTNO_PK PRIMARY KEY,
	DNAME 	VARCHAR2(20),
	LOC		VARCHAR2(13)
);

CREATE TABLE EMP_FK ( -- FK 지정용
	EMPNO	NUMBER			PRIMARY KEY, -- PK 이름 자동 생성
	ENAME 	VARCHAR2(20)	NOT NULL,
	JOB		VARCHAR2(10),
	MGR		NUMBER,
	DEPTNO NUMBER CONSTRAINT EMPFK_DEPTNO_FK REFERENCES DEPT_FK(DEPTNO) NOT NULL
);

CREATE TABLE EMP_FK ( -- FK 지정용
	EMPNO	NUMBER			PRIMARY KEY, -- PK 이름 자동 생성
	ENAME 	VARCHAR2(20)	NOT NULL,
	JOB		VARCHAR2(10),
	MGR		NUMBER,
	DEPTNO NUMBER NOT NULL 
		CONSTRAINT EMPFK_DEPTNO_FK
		REFERENCES DEPT_FK(DEPTNO)
		ON DELETE CASCADE -- 부모의 PK값을 지우면 해당 데이터도 같이 삭제
);

SELECT * FROM DEPT_FK;
SELECT * FROM EMP_FK;

-- 기존 제약조건 삭제
ALTER TABLE EMP_FK
DROP CONSTRAINT EMPFK_DEPTNO_FK;

-- CASCADE로 재설정
ALTER TABLE EMP_FK
ADD CONSTRAINT EMPFK_DEPTNO_FK
	FOREIGN KEY (DEPTNO)
	REFERENCES DEPT_FK(DEPTNO)
	ON DELETE CASCADE;

-- 전부 초기화. 자식테이블부터 삭제
TRUNCATE TABLE EMP_FK;
TRUNCATE TABLE DEPT_FK;

INSERT ALL
INTO DEPT_FK (DEPTNO, DNAME, LOC) VALUES (10, 'DEV', 'SEOUL')
INTO DEPT_FK (DEPTNO, DNAME, LOC) VALUES (20, 'ACCOUNTING', 'INCHEON')
INTO DEPT_FK (DEPTNO, DNAME, LOC) VALUES (30, 'FINANCE', 'BUSAN')
SELECT * FROM DUAL;

INSERT INTO EMP_FK (EMPNO, ENAME, DEPTNO)
VALUES (1000, '성유고', 20);

INSERT INTO EMP_FK (EMPNO, ENAME, DEPTNO, JOB, MGR)
VALUES (2000, '애슐리', 30, 'PRESIDENT', NULL);

DELETE FROM DEPT_FK 
WHERE DEPTNO = 20;

SELECT * FROM DEPT_FK;
SELECT * FROM EMP_FK;