CREATE OR REPLACE FUNCTION FNC_AFTERTAX(
	sal IN NUMBER
) RETURN NUMBER
IS
	tax NUMBER := 0.05;
BEGIN
	RETURN ROUND(sal - (sal * tax));
END FNC_AFTERTAX;

-- 함수 실행
SELECT FNC_AFTERTAX(3000) FROM DUAL;

-- SELECT문에 함수를 사용가능
SELECT EMPNO, ENAME, SAL
	 , FNC_AFTERTAX(SAL) AS aftertax
	 , TO_CHAR(HIREDATE, 'YYYY-MM-DD')
  FROM EMP;

-- 함수 삭제
DROP FUNCTION FNC_AFTERTAX;