-- 테스트용 EMP 테이블 생성
CREATE TABLE EMP_TRG
AS SELECT * FROM EMP;

-- DML 트리거 AFTER 테이블 생성
CREATE TABLE EMP_TRG_LOG(
	tablename VARCHAR2(20), -- dml이 수행된 테이블명
	dml_type VARCHAR2(10),
	empno NUMBER(4),
	user_name VARCHAR2(30),
	change_date DATE -- dml 수행한 일시
);

-- EMP_TRG에 실행
INSERT INTO EMP_TRG
VALUES (9997, 'EMPORI', 'CLERK', 7788, SYSDATE, 1200, NULL, 20);

UPDATE EMP_TRG
   SET MGR = 9995
 WHERE EMPNO = 9997;

DELETE FROM EMP_TRG 
 WHERE EMPNO = 9997;

SELECT * FROM EMP_TRG;

SELECT * FROM EMP_TRG_LOG;