-- orclstudy로 실행
CREATE TABLE SAMPLETBL (
	ST_IDX NUMBER(4) PRIMARY KEY,
	CONTENT VARCHAR2(200) NOT NULL,
	CODE CHAR(8) NOT NULL,
	REG_DATE DATE DEFAULT sysdate
);

SELECT * FROM SAMPLETBL;

INSERT INTO SAMPLETBL (ST_IDX, CONTENT, CODE)
VALUES (1, '컨텐츠에요', '00000001');

-- 권한 해제하고 재접속하면 생성 불가
CREATE TABLE SAMPLETBL2 (
	ST_IDX NUMBER(4) PRIMARY KEY,
	CONTENT VARCHAR2(200) NOT NULL,
	CODE CHAR(8) NOT NULL,
	REG_DATE DATE DEFAULT sysdate
);
