-- 예외처리
DECLARE
	v_wrong NUMBER;
BEGIN
	SELECT DNAME INTO v_wrong
	  FROM DEPT
	 WHERE DEPTNO = 10;
EXCEPTION
--	WHEN value_error THEN
--		DBMS_OUTPUT.PUT_LINE('예외처리 : 수치/값 오류 발생');
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('예외처리 : 예외 발생');
		DBMS_OUTPUT.PUT_LINE('SQLCODE : ' || TO_CHAR(SQLCODE));
		DBMS_OUTPUT.PUT_LINE('SQLERRM : ' || TO_CHAR(SQLERRM));
END;
