-- 그룹화
-- 테이블 데이터도 사용이 어렵고, 쿼리가 복잡해짐
SELECT AVG(SALARY), 1 FROM EMPLOYEE WHERE DEPT_ID = 1
UNION ALL
SELECT AVG(SALARY), 2 FROM EMPLOYEE WHERE DEPT_ID = 2
UNION ALL
SELECT AVG(SALARY), 3 FROM EMPLOYEE WHERE DEPT_ID = 3
UNION ALL
SELECT AVG(SALARY), 4 FROM EMPLOYEE WHERE DEPT_ID = 4;

-- 그룹화를 하면 간결해짐
SELECT AVG(SALARY), DEPT_ID
FROM EMPLOYEE
GROUP BY DEPT_ID
ORDER BY DEPT_ID;

-- 다중행 함수를 사용할 때
-- 일반 컬럼을 사용하려면 무조건!
-- GROUP BY에 추가해야 함
SELECT AVG(SALARY), COUNT(SALARY), DEPT_ID 
FROM EMPLOYEE
GROUP BY DEPT_ID;

-- HAVING절, 다중행의 필터링
SELECT AVG(SALARY), COUNT(SALARY), DEPT_ID 
FROM EMPLOYEE
-- WHERE SALARY <= 8000 -- 일반값 필터링
GROUP BY DEPT_ID
HAVING AVG(SALARY) >= 6000; -- 다중행 함수 필터링

-- 그룹화 통계
SELECT DEPT_ID, AVG(SALARY), COUNT(SALARY) 
FROM EMPLOYEE
GROUP BY ROLLUP(DEPT_ID);

SELECT NVL(TO_CHAR(DEPT_ID), '--총계--') AS "부서"
	 , AVG(SALARY), COUNT(SALARY) 
FROM EMPLOYEE
GROUP BY ROLLUP(DEPT_ID)
ORDER BY DEPT_ID;

