-- 부서 테이블의 데이터 개수 확인
SELECT COUNT(*) FROM DEPARTMENT; -- 한 줄 실행 Ctrl + Enter
SELECT COUNT(*) FROM EMPLOYEE;
SELECT COUNT(*) FROM CUSTOMER;
SELECT COUNT(*) FROM PRODUCT;
SELECT COUNT(*) FROM ORDERS;
SELECT COUNT(*) FROM ORDER_ITEM;

-- 주문 테이블에서 앞쪽 데이터 5개만 조회
-- 주문 테이블에서 앞쪽 데이터 5개만 조회
SELECT * FROM ORDERS WHERE rownum < 5;


