-- JOIN
SELECT d.DEPTNO, d.DNAME, d.LOC
	 , e.EMPNO, e.ENAME, e.JOB
	 , TO_CHAR(e.HIREDATE, 'YYYY-MM-DD') AS HIREDATE
	 , e.SAL    
FROM EMP e JOIN DEPT d
ON d.DEPTNO = e.DEPTNO;

-- INNER JOIN
SELECT d.DEPTNO, d.DNAME, d.LOC
	 , e.EMPNO, e.ENAME, e.JOB
	 , TO_CHAR(e.HIREDATE, 'YYYY-MM-DD') AS HIREDATE
	 , e.SAL    
FROM EMP e INNER JOIN DEPT d
ON d.DEPTNO = e.DEPTNO
WHERE d.DEPTNO = 30;

-- OUTER JOIN
SELECT d.DEPTNO, d.DNAME, d.LOC
	 , e.EMPNO, e.ENAME, e.JOB
	 , TO_CHAR(e.HIREDATE, 'YYYY-MM-DD') AS HIREDATE
	 , e.SAL    
FROM DEPT d LEFT OUTER JOIN EMP e
ON d.DEPTNO = e.DEPTNO;

SELECT d.DEPTNO, d.DNAME, d.LOC
	 , e.EMPNO, e.ENAME, e.JOB
	 , TO_CHAR(e.HIREDATE, 'YYYY-MM-DD') AS HIREDATE
	 , e.SAL    
FROM DEPT d RIGHT OUTER JOIN EMP e
ON d.DEPTNO = e.DEPTNO;

-- 세 테이블 조인 쿼리
SELECT d.DEPTNO, d.DNAME
	 , e.EMPNO, e.ENAME, e.JOB, e.SAL
	 , s.GRADE
FROM EMP e
INNER JOIN DEPT d
ON e.DEPTNO = d.DEPTNO
JOIN SALGRADE s
ON e.SAL BETWEEN s.LOSAL AND s.HISAL
ORDER BY d.DEPTNO, e.EMPNO;

-- 오라클 쿼리로
SELECT d.DEPTNO, d.DNAME
	 , e.EMPNO, e.ENAME, e.JOB, e.SAL
	 , s.GRADE
FROM EMP e, DEPT d, SALGRADE s
WHERE e.DEPTNO = d.DEPTNO
AND e.SAL BETWEEN s.LOSAL AND s.HISAL
ORDER BY d.DEPTNO, e.EMPNO;