-- 트랜잭션

-- DEPT테이블 복사
CREATE TABLE DEPT_TCL
	AS SELECT *
	   FROM dept;

SELECT * FROM DEPT_TCL;

-- 트랜잭션 시작
COMMIT;

INSERT INTO DEPT_TCL (DEPTNO, DNAME, LOC)
VALUES (60, 'UNIT TEST', 'DELI');

ROLLBACK;

-- 트랜잭션 시작2
INSERT INTO DEPT_TCL (DEPTNO, DNAME, LOC)
VALUES (60, 'UNIT TEST', 'DELI');

UPDATE DEPT_TCL SET LOC = 'BUSAN'
 WHERE DEPTNO = 40;

DELETE FROM DEPT_TCL WHERE DNAME = 'RESEARCH';

DELETE FROM EMP_TEMP WHERE EMPNO = 9999;

SELECT * FROM DEPT_TCL;
SELECT * FROM EMP_TEMP;

COMMIT;
ROLLBACK;

DELETE FROM EMP_TEMP;

SELECT * FROM EMP_TEMP;

-- 세션, 락
SELECT * FROM DEPT_TCL;

UPDATE DEPT_TCL
   SET LOC = 'INCHOEN'
 WHERE DEPTNO = 30;

COMMIT;

-- 락2
DELETE FROM DEPT_TCL WHERE DEPTNO = 60;

ROLLBACK;